// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: exec/exec.proto

package exec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// each ExeSpec describes an executable as well as 2 lists.
// One is a set of instreams - named pipes that the process will read from.
// The other is a set of outstreams - named pipes that the process will output to.
// In addition to any pipes specified here, there is always one instream ("stdin")
// and one outstream ("stdout")
type ExeSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exename   string   `protobuf:"bytes,1,opt,name=exename,proto3" json:"exename,omitempty"`
	Instream  []string `protobuf:"bytes,2,rep,name=instream,proto3" json:"instream,omitempty"`
	Outstream []string `protobuf:"bytes,3,rep,name=outstream,proto3" json:"outstream,omitempty"`
}

func (x *ExeSpec) Reset() {
	*x = ExeSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exec_exec_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExeSpec) ProtoMessage() {}

func (x *ExeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_exec_exec_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExeSpec.ProtoReflect.Descriptor instead.
func (*ExeSpec) Descriptor() ([]byte, []int) {
	return file_exec_exec_proto_rawDescGZIP(), []int{0}
}

func (x *ExeSpec) GetExename() string {
	if x != nil {
		return x.Exename
	}
	return ""
}

func (x *ExeSpec) GetInstream() []string {
	if x != nil {
		return x.Instream
	}
	return nil
}

func (x *ExeSpec) GetOutstream() []string {
	if x != nil {
		return x.Outstream
	}
	return nil
}

type ExeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eid string `protobuf:"bytes,1,opt,name=eid,proto3" json:"eid,omitempty"`
}

func (x *ExeResponse) Reset() {
	*x = ExeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exec_exec_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExeResponse) ProtoMessage() {}

func (x *ExeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exec_exec_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExeResponse.ProtoReflect.Descriptor instead.
func (*ExeResponse) Descriptor() ([]byte, []int) {
	return file_exec_exec_proto_rawDescGZIP(), []int{1}
}

func (x *ExeResponse) GetEid() string {
	if x != nil {
		return x.Eid
	}
	return ""
}

var File_exec_exec_proto protoreflect.FileDescriptor

var file_exec_exec_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x65, 0x78, 0x65, 0x63, 0x2f, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x65, 0x78, 0x65, 0x63, 0x22, 0x5d, 0x0a, 0x07, 0x45, 0x78, 0x65, 0x53, 0x70,
	0x65, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x78, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x69, 0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x75, 0x74,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x1f, 0x0a, 0x0b, 0x45, 0x78, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x65, 0x69, 0x64, 0x32, 0x33, 0x0a, 0x04, 0x45, 0x78, 0x65, 0x63, 0x12,
	0x2b, 0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x65, 0x78, 0x65,
	0x63, 0x2e, 0x45, 0x78, 0x65, 0x53, 0x70, 0x65, 0x63, 0x1a, 0x11, 0x2e, 0x65, 0x78, 0x65, 0x63,
	0x2e, 0x45, 0x78, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1d, 0x5a, 0x1b,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x6c, 0x70, 0x6f, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x65, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_exec_exec_proto_rawDescOnce sync.Once
	file_exec_exec_proto_rawDescData = file_exec_exec_proto_rawDesc
)

func file_exec_exec_proto_rawDescGZIP() []byte {
	file_exec_exec_proto_rawDescOnce.Do(func() {
		file_exec_exec_proto_rawDescData = protoimpl.X.CompressGZIP(file_exec_exec_proto_rawDescData)
	})
	return file_exec_exec_proto_rawDescData
}

var file_exec_exec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_exec_exec_proto_goTypes = []interface{}{
	(*ExeSpec)(nil),     // 0: exec.ExeSpec
	(*ExeResponse)(nil), // 1: exec.ExeResponse
}
var file_exec_exec_proto_depIdxs = []int32{
	0, // 0: exec.Exec.Execute:input_type -> exec.ExeSpec
	1, // 1: exec.Exec.Execute:output_type -> exec.ExeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_exec_exec_proto_init() }
func file_exec_exec_proto_init() {
	if File_exec_exec_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_exec_exec_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExeSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exec_exec_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_exec_exec_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exec_exec_proto_goTypes,
		DependencyIndexes: file_exec_exec_proto_depIdxs,
		MessageInfos:      file_exec_exec_proto_msgTypes,
	}.Build()
	File_exec_exec_proto = out.File
	file_exec_exec_proto_rawDesc = nil
	file_exec_exec_proto_goTypes = nil
	file_exec_exec_proto_depIdxs = nil
}
